NAME = philo

CC = cc 
CFLAGS =  -Wall -Wextra -Werror

SRC = main.c utils.c init.c monitor.c routine.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) -pthread $(OBJ) -o $(NAME)
%.o: %.c
	$(CC)  -c $< -o $@
	
clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
